---
title: "Práctica Supervivencia 2.0"
author: "Irene Extremera Serrano"
date: "14/11/2020"
output: html_document
---

```{r}
  library(ggplot2)
  library(ggpubr)
  library(survminer)
  library(survival)

setwd('D:/Desktop/Remember/Estudios/Educación Formal/Máster/Máster Valencia/Bioestadística/Curso 2/Especialización/3 Supervivencia/Tarea')
linfoma <- read.csv("linfoma.dat", sep="")
attach(linfoma)
```

```{r}
# Tablas de frecuencias: variables categóricas
table(linfoma$GROUP)
table(linfoma$STATUS)
table(linfoma$SEX)
table(linfoma$AGE60)

# Diagrama de cajas: variable continua
par(mfrow=c(1,2))
boxplot(linfoma$KPS.PRE,col='PINK', main= 'KPS.PRE')
boxplot(linfoma$B3TODEATH,col='PINK', main= 'Tiempo de supervivencia')
```


```{r}
# Swimmer plot
      color <- c('BLUE','ORANGE')
      plot(B3TODEATH,1:length(B3TODEATH),xlim=c(0,15),xlab='Tiempo de muerte (Años)',
           ylab='Pacientes leucemia',col=color[GROUP], main='Swimmer Plot')
      points(B3TODEATH[STATUS==1],(1:length(B3TODEATH))[STATUS==1],
             pch=19,col=color[GROUP[STATUS==1]])
      for (i in 1:length(B3TODEATH)) lines(c(0,B3TODEATH[i]),c(i,i))
      abline(v=c(0,38),lty=c(1,2))
      text(7,50,'No radiados previamente',col=color[1])
      text(7,15,'Radiados previamente',col=color[2])

# Censurados y fallecidos. 
table(linfoma[,c(2,4)])

# Identificación de qué individuos concrétamente han o no fallecido
Surv(linfoma$B3TODEATH,linfoma$STATUS)
```

```{r}
# CURVAS DE KAPLAN-MEIER

# CONJUNTA

linfoma <- read.csv("linfoma.dat", sep="") # Cargamos los datos para volver a usar STATUS como numérica

km.linfoma <- survfit(Surv(B3TODEATH,STATUS)~1, data=linfoma) # Curvas de Kaplan-Meier

par(mfrow=c(1,2))
plot(km.linfoma,conf.int=TRUE, main='Curva de Supervivencia conjunta') #supervivencia
plot(km.linfoma,fun = "cumhaz", conf.int=TRUE, main='Curva de Riesgo conjunta') #riesgo
summary(km.linfoma)

```


```{r}

par(mfrow=c(1,3))
km.linfoma.sexo <- survfit(Surv(B3TODEATH,STATUS)~SEX, data=linfoma) # Curvas de Kaplan-Meier
ggsurvplot(km.linfoma.sexo, data = linfoma,
           conf.int = TRUE,
           conf.int.style = "step",
           surv.median.line = "hv",
           pval = TRUE) #p valor log rank

km.linfoma.grupo <- survfit(Surv(B3TODEATH,STATUS)~GROUP, data=linfoma) # Curvas de Kaplan-Meier
ggsurvplot(km.linfoma.grupo, data = linfoma,
           conf.int = TRUE,
           conf.int.style = "step",
           surv.median.line = "hv",
           pval = TRUE)

km.linfoma.edad <- survfit(Surv(B3TODEATH,STATUS)~AGE60, data=linfoma) # Curvas de Kaplan-Meier
ggsurvplot(km.linfoma.edad, data = linfoma,
           conf.int = TRUE,
           conf.int.style = "step",
           surv.median.line = "hv",
           pval = TRUE)
```


```{r}
# Por grupos

# SEXO

survdiff(Surv(B3TODEATH,STATUS)~SEX, data=linfoma) # test log-rank
survdiff(Surv(B3TODEATH,STATUS)~SEX, data=linfoma, rho=1) # test Breslow

# GRUPOS

survdiff(Surv(B3TODEATH,STATUS)~GROUP, data=linfoma) # test log-rank
survdiff(Surv(B3TODEATH,STATUS)~GROUP, data=linfoma, rho=1) # test Breslow

# EDAD

survdiff(Surv(B3TODEATH,STATUS)~AGE60, data=linfoma) # test log-rank
survdiff(Surv(B3TODEATH,STATUS)~AGE60, data=linfoma, rho=1) # test Breslow

```


```{r}
# Análisis de los residuos

# Modelo Final
ajuste_definitivo <- coxph(Surv(B3TODEATH,STATUS) ~ KPS.PRE. + GROUP + AGE60 +SEX + AGE60:SEX, linfoma)
summary(ajuste_definitivo) # Concordance: 0.765 / Todos los coeficientes incluida la interacción salen positivos
```



```{r}

# Riesgos proporcionales
PH.test <- cox.zph(ajuste_definitivo)
PH.test #no hay que poner stratos
par.tipicos <- par(mfrow=c(2,2))
plot(PH.test)
par(par.tipicos)

# Residuos Mantingala
  martingala <- ajuste_definitivo$residuals
  coxsnell <- linfoma$STATUS - martingala
  malla<-seq(0,4,length.out = 200)
  # Representación
  plot(density(coxsnell), main='Residuos Cox-Snell')
  lines(malla,dexp(malla,rate=1), col=2) 
  
# Residuos Deviance
  res.deviance <- resid(ajuste_definitivo,type="deviance")
  qqnorm(res.deviance)
  qqline(res.deviance)
  
  ks.test(res.deviance, "pnorm") # Son normales

# Observaciones influyentes
     res.dfbeta <- resid(ajuste_definitivo,type='dfbeta')        # Medidas dfbeta
               par.tipicos <- par(mfrow=c(2,3))
               indice = 1:nrow(res.dfbeta)
               for (i in 1:5) plot(indice,res.dfbeta[,i],type='h', xlab='observación',
                     ylab=paste('cambio en el coeficiente',(names(ajuste_definitivo$coef))[i], sep = " ")) # 15 y 22
               linfoma[c(15,22),]
     ggcoxdiagnostics(ajuste_definitivo, type = "dfbeta", linear.predictions = FALSE) 
   # No se aprecia en la distribución de los residuos ningún patrón que pueda indicar una faltade ajuste. Estos residuos parecen ser independientes del tiempo de              supervivencia.
               
# Observaciones anómalas
  plot(ajuste_definitivo$linear,res.deviance,type='p',ylab='Residuos deviance',
               xlab='Puntuaciones de riesgo'); abline(h=0) 
  order(res.deviance) 
  res.deviance[c(5,30,32,40,57)] # 5, 32 y 40
  linfoma[c(5,32,40),]

# Valores anómalos en las covariables
   res.partial <- resid(ajuste_definitivo,type='partial')
               tiempos <- as.numeric(rownames(res.partial))
            
                           # Añadiendo bandas de confianza
               par(mfrow=c(2,3))
               for (i in 1:5) {
                  sm.res <- loess(res.partial[,i] ~ tiempos)
                  destip <- predict(sm.res,se=T)$se
                  plot(tiempos,res.partial[,i],xlab='Tiempos ordenados',type='p',
                           ylab=paste('Residuos parciales para',(names(ajuste_definitivo$coef))[i], sep = " "))
                  lines(tiempos,sm.res$fit)
                  lines(tiempos,sm.res$fit+2*destip,lty=2)
                  lines(tiempos,sm.res$fit-2*destip,lty=2)}

# Colinealidad
  vif(ajuste_definitivo) # Son muy bajos
```












